;; Hermetica v7 CANDIDATE. A new deployment; never an upgrade of existing code.
;; Exactly ONE upstream claim can be outstanding. Completed claims become durable
;; per-user receipts. A third party may redeem/delete the upstream claim safely.
;; Free balance = sBTC balance - all credited receipts. Only its increase since
;; this singleton request belongs to its claimant. Baseline surplus is never swept.
;; Donations arriving during an outstanding claim benefit that claimant on settlement;
;; donations before a request or on a cancelled request remain inaccessible surplus.
;; Serialization blocks new deposits/requests until upstream funding/redemption or
;; cancellation. Any caller can settle; protocol pause/liquidity/cooldown still apply.
;; Mainnet bindings below are immutable. Local tests substitute PRINCIPALS ONLY.
(impl-trait .yield-source-async-v1.yield-source-async-v1-trait)
(use-trait sip-010-trait .sip-010-trait.sip-010-trait)
(define-constant CONTRACT-OWNER tx-sender)
(define-constant EXPECTED-GOVERNOR 'SMJSVT0J9K2DKM8QWXSHXPVTYPJBV4CC5P1ZXAW0)
(define-constant UPSTREAM 'SP1S1HSFH0SQQGWKB69EYFNY0B1MHRMGXR3J1FH4D.vault-hbtc-v1-2)
(define-constant ASSET 'SM3VDXK3WZZSA84XXFKAFAF15NNZX32CTSG82JFQ4.sbtc-token)
(define-constant err-not-owner (err u100))
(define-constant err-paused (err u101))
(define-constant err-zero-amount (err u102))
(define-constant err-not-vault (err u103))
(define-constant err-insufficient (err u104))
(define-constant err-apy-too-high (err u106))
(define-constant err-stale-apy (err u107))
(define-constant err-no-consensus (err u108))
(define-constant err-deviation (err u109))
(define-constant err-bad-oracle-idx (err u110))
(define-constant err-no-shares (err u120))
(define-constant err-no-claim (err u121))
(define-constant err-bad-token (err u122))
(define-constant err-duplicate (err u123))
(define-constant err-queue-busy (err u130))
(define-constant err-invariant (err u131))
(define-constant err-upstream (err u132))
(define-constant err-lock (err u133))
(define-constant err-claim-settled (err u134))

(define-data-var adapter-paused bool true)
(define-data-var locked bool false)
(define-data-var total-shares uint u0)
(define-data-var total-principal uint u0)
(define-data-var receipt-liability uint u0)
(define-data-var pending (optional {user:principal,claim-id:uint,baseline-free:uint}) none)
(define-map user-shares principal uint)
(define-map user-principal principal uint)
(define-map user-claim principal uint)
(define-map receipts principal uint)

(define-private (assert-owner)
  (if (is-eq contract-caller CONTRACT-OWNER) (ok true) err-not-owner))
(define-private (assert-vault)
  (if (is-eq contract-caller .vault-v7) (ok true) err-not-vault))
(define-private (lock)
  (begin (asserts! (not (var-get locked)) err-lock) (var-set locked true) (ok true)))
(define-private (unlock) (var-set locked false))
(define-private (asset-balance)
  (unwrap-panic (contract-call? 'SM3VDXK3WZZSA84XXFKAFAF15NNZX32CTSG82JFQ4.sbtc-token get-balance (as-contract tx-sender))))
(define-private (free-balance)
  (let ((balance (asset-balance)))
    (asserts! (>= balance (var-get receipt-liability)) err-invariant)
    (ok (- balance (var-get receipt-liability)))))
(define-private (check-governance)
  (begin
    (asserts! (is-eq EXPECTED-GOVERNOR (contract-call? 'SP1S1HSFH0SQQGWKB69EYFNY0B1MHRMGXR3J1FH4D.hq-v1 get-owner)) err-upstream)
    (asserts! (contract-call? 'SP1S1HSFH0SQQGWKB69EYFNY0B1MHRMGXR3J1FH4D.hq-v1 get-protocol UPSTREAM) err-upstream)
    (ok true)))
(define-private (check-principal (amount uint) (user principal))
  (begin
    (asserts! (is-eq amount (unwrap! (map-get? user-principal user) err-no-shares)) err-insufficient)
    (ok true)))

(define-public (deposit (amount uint) (user principal))
  (begin
    (try! (assert-vault)) (try! (lock)) (try! (check-governance))
    (asserts! (not (var-get adapter-paused)) err-paused)
    (asserts! (is-none (var-get pending)) err-queue-busy)
    (asserts! (> amount u0) err-zero-amount)
    (asserts! (is-none (map-get? user-principal user)) err-duplicate)
    (let ((before (try! (free-balance))))
      ;; vault-v7 has already transferred exactly this deposit to the adapter.
      (asserts! (>= before amount) err-invariant)
      (let ((shares (try! (as-contract (contract-call? 'SP1S1HSFH0SQQGWKB69EYFNY0B1MHRMGXR3J1FH4D.vault-hbtc-v1-2 deposit amount none)))))
        (asserts! (> shares u0) err-no-shares)
        (asserts! (is-eq (try! (free-balance)) (- before amount)) err-invariant)
        (map-set user-shares user shares)
        (map-set user-principal user amount)
        (var-set total-shares (+ (var-get total-shares) shares))
        (var-set total-principal (+ (var-get total-principal) amount))
        (unlock)
        (ok shares)))))

(define-public (request-withdraw (amount uint) (user principal))
  (begin
    (try! (assert-vault)) (try! (lock)) (try! (check-principal amount user))
    (asserts! (is-none (var-get pending)) err-queue-busy)
    (asserts! (is-none (map-get? user-claim user)) err-duplicate)
    (let ((shares (unwrap! (map-get? user-shares user) err-no-shares))
          (baseline (try! (free-balance))))
      (let ((id (try! (as-contract (contract-call? 'SP1S1HSFH0SQQGWKB69EYFNY0B1MHRMGXR3J1FH4D.vault-hbtc-v1-2 request-redeem shares false)))))
        (let ((claim (try! (contract-call? 'SP1S1HSFH0SQQGWKB69EYFNY0B1MHRMGXR3J1FH4D.vault-hbtc-v1-2 get-claim id))))
          (asserts! (is-eq (get user claim) (as-contract tx-sender)) err-upstream)
          (asserts! (is-eq (get shares claim) shares) err-upstream)
          (asserts! (is-none (get assets claim)) err-upstream)
          (asserts! (is-eq baseline (try! (free-balance))) err-invariant)
          (map-set user-claim user id)
          (var-set pending (some {user:user,claim-id:id,baseline-free:baseline}))
          (unlock)
          (print {event:"hbtc-request-v7",user:user,claim-id:id,baseline-free:baseline})
          (ok id))))))

;; Caller holds adapter lock. Only upstream NO_CLAIM (103003) allows receipt
;; recovery without a new redeem. Verified immutable upstream code can delete a
;; claim only after payment or owner-authorized cancellation; our cancel clears
;; this pending record atomically. Neither governance nor blacklist deletes it.
(define-private (settle)
  (let ((entry (unwrap! (var-get pending) err-no-claim)))
    (let ((user (get user entry)) (id (get claim-id entry))
          (before (try! (free-balance)))
          (shares (unwrap! (map-get? user-shares (get user entry)) err-no-shares)))
      (asserts! (is-none (map-get? receipts user)) err-duplicate)
      (asserts! (>= before (get baseline-free entry)) err-invariant)
      (match (contract-call? 'SP1S1HSFH0SQQGWKB69EYFNY0B1MHRMGXR3J1FH4D.vault-hbtc-v1-2 get-claim id)
        claim
          (begin
            (asserts! (is-eq (get user claim) (as-contract tx-sender)) err-upstream)
            (asserts! (is-eq (get shares claim) shares) err-upstream)
            ;; fund-claim is permissionless after cooldown; all failures propagate.
            (if (is-none (get assets claim))
              (begin (try! (contract-call? 'SP1S1HSFH0SQQGWKB69EYFNY0B1MHRMGXR3J1FH4D.vault-hbtc-v1-2 fund-claim id)) true)
              true)
            (let ((paid (try! (contract-call? 'SP1S1HSFH0SQQGWKB69EYFNY0B1MHRMGXR3J1FH4D.vault-hbtc-v1-2 redeem id)))
                  (after (try! (free-balance))))
              (asserts! (>= after before) err-invariant)
              (asserts! (is-eq (- after before) paid) err-invariant)))
        error (asserts! (is-eq error u103003) (err error)))
      (let ((free (try! (free-balance))))
        (asserts! (>= free (get baseline-free entry)) err-invariant)
        (let ((credit (- free (get baseline-free entry))))
          (map-set receipts user credit)
          (var-set receipt-liability (+ (var-get receipt-liability) credit))
          (map-delete user-shares user)
          (var-set total-shares (- (var-get total-shares) shares))
          (var-set pending none)
          (asserts! (is-eq (try! (free-balance)) (get baseline-free entry)) err-invariant)
          (print {event:"hbtc-settled-v7",user:user,claim-id:id,credit:credit})
          (ok credit))))))

;; Permissionless queue advancement. Creates a durable receipt; sends no funds.
(define-public (settle-pending)
  (begin (try! (lock))
    (let ((credit (try! (settle)))) (unlock) (ok credit))))

(define-public (claim-withdraw (amount uint) (user principal) (sbtc <sip-010-trait>))
  (begin
    (try! (assert-vault)) (try! (lock)) (try! (check-principal amount user))
    (asserts! (is-eq (contract-of sbtc) ASSET) err-bad-token)
    (if (is-none (map-get? receipts user))
      (begin
        (asserts! (is-eq user (get user (unwrap! (var-get pending) err-no-claim))) err-no-claim)
        (try! (settle)) true)
      true)
    (let ((credit (unwrap! (map-get? receipts user) err-no-claim))
          (before (try! (free-balance))))
      (map-delete receipts user)
      (map-delete user-principal user)
      (map-delete user-claim user)
      (var-set total-principal (- (var-get total-principal) amount))
      (var-set receipt-liability (- (var-get receipt-liability) credit))
      (if (> credit u0)
        (asserts! (try! (as-contract (contract-call? sbtc transfer credit tx-sender .vault-v7 none))) err-invariant)
        true)
      ;; Paying A while B is pending reduces balance and liabilities equally.
      (asserts! (is-eq (try! (free-balance)) before) err-invariant)
      (unlock)
      (ok credit))))

(define-public (cancel-withdraw (amount uint) (user principal))
  (begin
    (try! (assert-vault)) (try! (lock)) (try! (check-principal amount user))
    (asserts! (is-none (map-get? receipts user)) err-claim-settled)
    (let ((entry (unwrap! (var-get pending) err-no-claim))
          (shares (unwrap! (map-get? user-shares user) err-no-shares))
          (before (try! (free-balance))))
      (asserts! (is-eq user (get user entry)) err-no-claim)
      (asserts! (is-eq shares (try! (as-contract (contract-call? 'SP1S1HSFH0SQQGWKB69EYFNY0B1MHRMGXR3J1FH4D.vault-hbtc-v1-2 cancel-redeem (get claim-id entry))))) err-invariant)
      (asserts! (is-eq (try! (free-balance)) before) err-invariant)
      (map-delete user-claim user)
      (var-set pending none)
      (unlock)
      (ok true))))

(define-public (set-paused (value bool))
  (begin (try! (assert-owner)) (var-set adapter-paused value) (ok value)))
(define-read-only (get-shares (user principal)) (default-to u0 (map-get? user-shares user)))
(define-read-only (get-claim-id (user principal)) (map-get? user-claim user))
(define-read-only (get-receipt (user principal)) (map-get? receipts user))
(define-read-only (get-pending) (var-get pending))
(define-read-only (get-receipt-liability) (var-get receipt-liability))
;; Principal metric, deliberately not an oracle-derived claim of current NAV.
(define-read-only (get-total-deposited) (ok (var-get total-principal)))
(define-read-only (get-total-shares) (var-get total-shares))
(define-read-only (preview-deposit (amount uint))
  (ok (contract-call? 'SP1S1HSFH0SQQGWKB69EYFNY0B1MHRMGXR3J1FH4D.vault-hbtc-v1-2 preview-deposit amount)))
(define-read-only (get-accounting)
  (let ((balance (asset-balance)))
    (asserts! (>= balance (var-get receipt-liability)) err-invariant)
    (ok {balance:balance,liability:(var-get receipt-liability),free:(- balance (var-get receipt-liability))})))
(define-read-only (preview-withdraw (user principal))
  (match (map-get? receipts user)
    receipt (ok receipt)
    (let ((shares (unwrap! (map-get? user-shares user) err-no-shares)))
      (match (map-get? user-claim user)
        id
          (let ((entry (unwrap! (var-get pending) err-no-claim))
                (accounting (try! (get-accounting))))
            (asserts! (is-eq user (get user entry)) err-invariant)
            (asserts! (>= (get free accounting) (get baseline-free entry)) err-invariant)
            (let ((donations (- (get free accounting) (get baseline-free entry))))
              (match (contract-call? 'SP1S1HSFH0SQQGWKB69EYFNY0B1MHRMGXR3J1FH4D.vault-hbtc-v1-2 get-claim id)
                claim
                  (let ((assets (default-to (contract-call? 'SP1S1HSFH0SQQGWKB69EYFNY0B1MHRMGXR3J1FH4D.vault-hbtc-v1-2 preview-redeem shares) (get assets claim))))
                    (asserts! (is-eq (get user claim) (as-contract tx-sender)) err-upstream)
                    (asserts! (is-eq (get shares claim) shares) err-upstream)
                    (ok (+ donations (- assets (default-to (/ (* assets (get fee-bps claim)) u10000) (get fee claim))))))
                error (if (is-eq error u103003) (ok donations) (err error)))))
        (let ((assets (contract-call? 'SP1S1HSFH0SQQGWKB69EYFNY0B1MHRMGXR3J1FH4D.vault-hbtc-v1-2 preview-redeem shares))
              (fee-bps (contract-call? 'SP1S1HSFH0SQQGWKB69EYFNY0B1MHRMGXR3J1FH4D.state-hbtc-v1 get-custom-exit-fee (as-contract tx-sender) false)))
          (ok (- assets (/ (* assets fee-bps) u10000))))))))

(define-read-only (is-paused)
  (ok (or (var-get adapter-paused) (is-some (var-get pending))
    (not (is-eq EXPECTED-GOVERNOR (contract-call? 'SP1S1HSFH0SQQGWKB69EYFNY0B1MHRMGXR3J1FH4D.hq-v1 get-owner)))
    (not (contract-call? 'SP1S1HSFH0SQQGWKB69EYFNY0B1MHRMGXR3J1FH4D.hq-v1 get-protocol UPSTREAM))
    (not (contract-call? 'SP1S1HSFH0SQQGWKB69EYFNY0B1MHRMGXR3J1FH4D.hq-v1 get-protocol-enabled))
    (not (contract-call? 'SP1S1HSFH0SQQGWKB69EYFNY0B1MHRMGXR3J1FH4D.state-hbtc-v1 get-vault-enabled))
    (not (contract-call? 'SP1S1HSFH0SQQGWKB69EYFNY0B1MHRMGXR3J1FH4D.state-hbtc-v1 get-deposit-enabled)))))

;; Two-of-three fresh oracle reports. Does not price shares or authorize exits.
(define-constant APY-CAP            u6000)
(define-constant STALE-BLOCKS       u144) ;; Bitcoin burn blocks
(define-constant CONSENSUS-TOL-PCT  u10)
(define-constant MAX-DEVIATION-PCT  u50)
(define-constant ORACLE-COUNT       u3)

(define-data-var current-apy-bps uint u0)
(define-data-var last-updated-block uint u0)
(define-map oracle-principals uint principal)
(define-map oracle-reports uint uint)
(define-map oracle-report-block uint uint)
(define-private (is-oracle (caller principal))
  (or (is-eq caller (default-to 'SP000000000000000000002Q6VF78 (map-get? oracle-principals u0)))
      (is-eq caller (default-to 'SP000000000000000000002Q6VF78 (map-get? oracle-principals u1)))
      (is-eq caller (default-to 'SP000000000000000000002Q6VF78 (map-get? oracle-principals u2)))))

(define-private (oracle-index-of (caller principal))
  (if (is-eq caller (default-to 'SP000000000000000000002Q6VF78 (map-get? oracle-principals u0)))
    (some u0)
    (if (is-eq caller (default-to 'SP000000000000000000002Q6VF78 (map-get? oracle-principals u1)))
      (some u1)
      (if (is-eq caller (default-to 'SP000000000000000000002Q6VF78 (map-get? oracle-principals u2)))
        (some u2)
        none))))

(define-private (abs-diff (a uint) (b uint))
  (if (>= a b) (- a b) (- b a)))

(define-private (is-fresh (idx uint))
  (let ((b (default-to u0 (map-get? oracle-report-block idx))))
    (and (> b u0) (<= (- burn-block-height b) STALE-BLOCKS))))

(define-private (try-commit-consensus (new-bps uint))
  (let
    ((r0    (default-to u0 (map-get? oracle-reports u0)))
     (r1    (default-to u0 (map-get? oracle-reports u1)))
     (r2    (default-to u0 (map-get? oracle-reports u2)))
     (live0 (is-fresh u0))
     (live1 (is-fresh u1))
     (live2 (is-fresh u2)))
    (if (and live0 live1 (<= (* u100 (abs-diff r0 r1)) (* CONSENSUS-TOL-PCT r1)))
      (ok { bps: (/ (+ r0 r1) u2), at: (min (default-to u0 (map-get? oracle-report-block u0)) (default-to u0 (map-get? oracle-report-block u1))) })
      (if (and live0 live2 (<= (* u100 (abs-diff r0 r2)) (* CONSENSUS-TOL-PCT r2)))
        (ok { bps: (/ (+ r0 r2) u2), at: (min (default-to u0 (map-get? oracle-report-block u0)) (default-to u0 (map-get? oracle-report-block u2))) })
        (if (and live1 live2 (<= (* u100 (abs-diff r1 r2)) (* CONSENSUS-TOL-PCT r2)))
          (ok { bps: (/ (+ r1 r2) u2), at: (min (default-to u0 (map-get? oracle-report-block u1)) (default-to u0 (map-get? oracle-report-block u2))) })
          err-no-consensus)))))

(define-private (min (a uint) (b uint)) (if (< a b) a b))
(define-public (set-apy (bps uint))
  (let ((caller contract-caller))
    (asserts! (is-eq caller tx-sender) err-not-owner)
    (asserts! (is-oracle caller) err-not-owner)
    (asserts! (<= bps APY-CAP) err-apy-too-high)
    (let ((current (var-get current-apy-bps))
          (idx     (unwrap! (oracle-index-of caller) err-not-owner)))
      (asserts!
        (or (is-eq current u0)
            (<= (* u100 (abs-diff bps current)) (* MAX-DEVIATION-PCT current)))
        err-deviation)
      (map-set oracle-reports      idx bps)
      (map-set oracle-report-block idx burn-block-height)
      (match (try-commit-consensus bps)
        committed-bps (begin
          (var-set current-apy-bps (get bps committed-bps))
          (var-set last-updated-block (get at committed-bps))
          (ok (get bps committed-bps)))
        e (ok (var-get current-apy-bps))))))

(define-public (set-oracle-at (idx uint) (oracle principal))
  (begin
    (try! (assert-owner))
    (asserts! (< idx ORACLE-COUNT) err-bad-oracle-idx)
    (asserts! (or (is-none (oracle-index-of oracle))
                   (is-eq (oracle-index-of oracle) (some idx))) err-duplicate)
    (map-set oracle-principals idx oracle)
    (map-delete oracle-reports idx)
    (map-delete oracle-report-block idx)
    (var-set last-updated-block u0)
    (ok oracle)))

(define-read-only (get-apy)
  (let ((last (var-get last-updated-block)))
    (if (or (is-eq last u0) (> burn-block-height (+ last STALE-BLOCKS)))
      err-stale-apy
      (ok (var-get current-apy-bps)))))

(define-read-only (get-last-updated-block) (ok (var-get last-updated-block)))

(define-read-only (get-oracle-report (idx uint))
  (ok { bps:   (default-to u0 (map-get? oracle-reports idx))
      , block: (default-to u0 (map-get? oracle-report-block idx)) }))

(define-read-only (get-oracle (idx uint))
  (map-get? oracle-principals idx))

