;; SatoshiYield v7 candidate. Separate deployment; does not upgrade live v6.
;; No strategy is enabled at deployment and deposits start paused.
;; Positions and risk budgets are isolated per user/adapter. Underlying strategy
;; solvency, liquidity and custody remain external risks; principal is not insured.
(use-trait sync .yield-source-v2.yield-source-v2-trait)
(use-trait async .yield-source-async-v1.yield-source-async-v1-trait)
(use-trait token .sip-010-trait.sip-010-trait)

(define-constant OWNER tx-sender)
(define-constant DELAY u144) ;; Bitcoin burn blocks, approximately one day.
(define-constant MIN-DEPOSIT u1000)
(define-constant MAX-FEE u1000)
(define-constant ERR-AUTH (err u100))
(define-constant ERR-PAUSED (err u101))
(define-constant ERR-CAP (err u103))
(define-constant ERR-AMOUNT (err u104))
(define-constant ERR-POSITION (err u105))
(define-constant ERR-FEE (err u106))
(define-constant ERR-ADAPTER (err u107))
(define-constant ERR-EXISTS (err u109))
(define-constant ERR-TIMELOCK (err u110))
(define-constant ERR-PENDING (err u111))
(define-constant ERR-TOKEN (err u115))
(define-constant ERR-INIT (err u116))
(define-constant ERR-LOCK (err u118))
(define-constant ERR-KIND (err u119))
(define-constant ERR-STATUS (err u120))
(define-constant ERR-BALANCE (err u122))
(define-constant ERR-SLIPPAGE (err u123))
(define-constant ERR-DIRECT (err u124))

(define-data-var paused bool true)
(define-data-var locked bool false)
(define-data-var sbtc (optional principal) none)
(define-data-var tvl-cap uint u50000000)
(define-data-var deposited uint u0)
(define-data-var fee-bps uint u500)
(define-data-var fee-balance uint u0)
(define-data-var fee-collector principal OWNER)
(define-data-var pending-fee (optional {bps:uint,at:uint}) none)
(define-data-var pending-collector (optional {collector:principal,at:uint}) none)
(define-map adapters principal {enabled:bool,is-async:bool,cap:uint})
(define-map pending-adapters principal {is-async:bool,cap:uint,at:uint})
(define-map adapter-deposited principal uint)
(define-map positions {user:principal,adapter:principal}
  {principal-amount:uint,deposited-at:uint,is-async:bool,status:uint,claim-id:uint,fee-bps:uint,credited-shares:uint})

(define-private (owner)
  (begin (asserts! (is-eq contract-caller OWNER) ERR-AUTH) (ok true)))
(define-private (direct)
  (begin (asserts! (is-eq tx-sender contract-caller) ERR-DIRECT) (ok true)))
(define-private (lock)
  (begin (asserts! (not (var-get locked)) ERR-LOCK) (var-set locked true) (ok true)))
(define-private (check-token (asset <token>))
  (begin (asserts! (is-eq (some (contract-of asset)) (var-get sbtc)) ERR-TOKEN) (ok true)))
(define-private (balance (asset <token>))
  (contract-call? asset get-balance (as-contract tx-sender)))
(define-private (check-deposit (adapter principal) (amount uint) (kind bool) (max-fee uint))
  (let ((config (unwrap! (map-get? adapters adapter) ERR-ADAPTER))
        (exposure (default-to u0 (map-get? adapter-deposited adapter))))
    (asserts! (not (var-get paused)) ERR-PAUSED)
    (asserts! (get enabled config) ERR-ADAPTER)
    (asserts! (is-eq kind (get is-async config)) ERR-KIND)
    (asserts! (>= amount MIN-DEPOSIT) ERR-AMOUNT)
    ;; Subtraction is guarded; never add untrusted uint amounts before checking.
    (asserts! (<= (var-get deposited) (var-get tvl-cap)) ERR-CAP)
    (asserts! (<= amount (- (var-get tvl-cap) (var-get deposited))) ERR-CAP)
    (asserts! (<= exposure (get cap config)) ERR-CAP)
    (asserts! (<= amount (- (get cap config) exposure)) ERR-CAP)
    (asserts! (<= (var-get fee-bps) max-fee) ERR-FEE)
    (asserts! (is-none (map-get? positions {user:tx-sender,adapter:adapter})) ERR-EXISTS)
    (ok true)))
(define-private (record-deposit (adapter principal) (amount uint) (kind bool) (shares uint))
  (begin
    (map-set positions {user:tx-sender,adapter:adapter}
      {principal-amount:amount,deposited-at:stacks-block-height,is-async:kind,status:u0,claim-id:u0,fee-bps:(var-get fee-bps),credited-shares:shares})
    (var-set deposited (+ (var-get deposited) amount))
    (map-set adapter-deposited adapter (+ (default-to u0 (map-get? adapter-deposited adapter)) amount))
    (var-set locked false)
    (print {event:"deposit-v7",user:tx-sender,adapter:adapter,amount:amount,shares:shares,fee-bps:(var-get fee-bps),async:kind})
    (ok shares)))
;; Division before multiplication bounds each term without losing integer precision.
(define-private (fee (profit uint) (bps uint))
  (+ (* (/ profit u10000) bps) (/ (* (mod profit u10000) bps) u10000)))
(define-private (settle (asset <token>) (adapter principal) (gross uint) (before uint) (minimum uint))
  (let ((position (unwrap! (map-get? positions {user:tx-sender,adapter:adapter}) ERR-POSITION))
        (after (try! (balance asset))))
    ;; A dishonest adapter cannot consume another position's assets or booked fees.
    (asserts! (>= after before) ERR-BALANCE)
    (asserts! (is-eq (- after before) gross) ERR-BALANCE)
    (let ((principal-amount (get principal-amount position))
          (profit (if (> gross (get principal-amount position)) (- gross (get principal-amount position)) u0)))
      (let ((charge (fee profit (get fee-bps position))))
        (let ((payout (- gross charge)) (user tx-sender))
          (asserts! (>= payout minimum) ERR-SLIPPAGE)
          (map-delete positions {user:user,adapter:adapter})
          (var-set deposited (- (var-get deposited) principal-amount))
          (map-set adapter-deposited adapter (- (default-to u0 (map-get? adapter-deposited adapter)) principal-amount))
          (var-set fee-balance (+ (var-get fee-balance) charge))
          ;; Total strategy loss can be acknowledged with minimum=0 without a zero transfer.
          (if (> payout u0)
            (asserts! (try! (as-contract (contract-call? asset transfer payout tx-sender user none))) ERR-BALANCE)
            true)
          (var-set locked false)
          (print {event:"withdraw-v7",user:user,adapter:adapter,gross:gross,payout:payout,fee:charge})
          (ok payout))))))

(define-public (set-sbtc-token (asset <token>))
  (begin
    (try! (owner))
    (asserts! (is-none (var-get sbtc)) ERR-INIT)
    (asserts! (is-eq (try! (contract-call? asset get-decimals)) u8) ERR-TOKEN)
    (var-set sbtc (some (contract-of asset)))
    (ok (contract-of asset))))

(define-public (deposit (asset <token>) (adapter <sync>) (amount uint) (min-shares uint) (max-fee-bps uint))
  (let ((target (contract-of adapter)))
    (try! (direct)) (try! (lock)) (try! (check-token asset))
    (try! (check-deposit target amount false max-fee-bps))
    (asserts! (> min-shares u0) ERR-SLIPPAGE)
    (asserts! (not (try! (contract-call? adapter is-paused))) ERR-PAUSED)
    (try! (contract-call? adapter get-apy))
    (asserts! (try! (contract-call? asset transfer amount tx-sender target none)) ERR-BALANCE)
    (let ((shares (try! (contract-call? adapter deposit amount tx-sender))))
      (asserts! (>= shares min-shares) ERR-SLIPPAGE)
      (record-deposit target amount false shares))))

(define-public (deposit-async (asset <token>) (adapter <async>) (amount uint) (min-shares uint) (max-fee-bps uint))
  (let ((target (contract-of adapter)))
    (try! (direct)) (try! (lock)) (try! (check-token asset))
    (try! (check-deposit target amount true max-fee-bps))
    (asserts! (> min-shares u0) ERR-SLIPPAGE)
    (asserts! (not (try! (contract-call? adapter is-paused))) ERR-PAUSED)
    (try! (contract-call? adapter get-apy))
    (asserts! (try! (contract-call? asset transfer amount tx-sender target none)) ERR-BALANCE)
    (let ((shares (try! (contract-call? adapter deposit amount tx-sender))))
      (asserts! (>= shares min-shares) ERR-SLIPPAGE)
      (record-deposit target amount true shares))))

(define-public (withdraw (asset <token>) (adapter <sync>) (min-payout uint))
  (let ((target (contract-of adapter))
        (position (unwrap! (map-get? positions {user:tx-sender,adapter:(contract-of adapter)}) ERR-POSITION)))
    (try! (direct)) (try! (lock)) (try! (check-token asset))
    (asserts! (not (get is-async position)) ERR-KIND)
    (let ((before (try! (balance asset))))
      (let ((gross (try! (contract-call? adapter withdraw (get principal-amount position) tx-sender asset))))
        (settle asset target gross before min-payout)))))

(define-public (request-withdraw (adapter <async>))
  (let ((target (contract-of adapter))
        (position (unwrap! (map-get? positions {user:tx-sender,adapter:(contract-of adapter)}) ERR-POSITION)))
    (try! (direct)) (try! (lock))
    (asserts! (get is-async position) ERR-KIND)
    (asserts! (is-eq (get status position) u0) ERR-STATUS)
    (let ((claim-id (try! (contract-call? adapter request-withdraw (get principal-amount position) tx-sender))))
      (map-set positions {user:tx-sender,adapter:target} (merge position {status:u1,claim-id:claim-id}))
      (var-set locked false)
      (print {event:"withdraw-requested-v7",user:tx-sender,adapter:target,claim-id:claim-id})
      (ok claim-id))))

(define-public (claim-withdraw (asset <token>) (adapter <async>) (min-payout uint))
  (let ((target (contract-of adapter))
        (position (unwrap! (map-get? positions {user:tx-sender,adapter:(contract-of adapter)}) ERR-POSITION)))
    (try! (direct)) (try! (lock)) (try! (check-token asset))
    (asserts! (get is-async position) ERR-KIND)
    (asserts! (is-eq (get status position) u1) ERR-STATUS)
    (let ((before (try! (balance asset))))
      (let ((gross (try! (contract-call? adapter claim-withdraw (get principal-amount position) tx-sender asset))))
        (settle asset target gross before min-payout)))))

(define-public (cancel-withdraw (adapter <async>))
  (let ((target (contract-of adapter))
        (position (unwrap! (map-get? positions {user:tx-sender,adapter:(contract-of adapter)}) ERR-POSITION)))
    (try! (direct)) (try! (lock))
    (asserts! (get is-async position) ERR-KIND)
    (asserts! (is-eq (get status position) u1) ERR-STATUS)
    (asserts! (try! (contract-call? adapter cancel-withdraw (get principal-amount position) tx-sender)) ERR-STATUS)
    (map-set positions {user:tx-sender,adapter:target} (merge position {status:u0,claim-id:u0}))
    (var-set locked false)
    (print {event:"withdraw-cancelled-v7",user:tx-sender,adapter:target})
    (ok true)))

;; Onboarding and cap increases require notice; removal blocks deposits only.
;; Replacing a pending proposal cancels the old proposal. Revoke cancels it too.
(define-public (schedule-adapter (adapter principal) (is-async bool) (cap uint))
  (let ((at (+ burn-block-height DELAY)))
    (try! (owner))
    (asserts! (>= cap MIN-DEPOSIT) ERR-CAP)
    (map-set pending-adapters adapter {is-async:is-async,cap:cap,at:at})
    (print {event:"adapter-scheduled-v7",adapter:adapter,is-async:is-async,cap:cap,at:at})
    (ok at)))
(define-public (apply-adapter (adapter principal))
  (let ((pending (unwrap! (map-get? pending-adapters adapter) ERR-PENDING))
        (exposure (default-to u0 (map-get? adapter-deposited adapter))))
    (asserts! (>= burn-block-height (get at pending)) ERR-TIMELOCK)
    (asserts! (>= (get cap pending) exposure) ERR-CAP)
    (match (map-get? adapters adapter) old
      (asserts! (or (is-eq exposure u0) (is-eq (get is-async old) (get is-async pending))) ERR-KIND) true)
    (map-set adapters adapter {enabled:true,is-async:(get is-async pending),cap:(get cap pending)})
    (map-delete pending-adapters adapter)
    (print {event:"adapter-enabled-v7",adapter:adapter,is-async:(get is-async pending),cap:(get cap pending)})
    (ok true)))
(define-public (revoke-adapter (adapter principal))
  (begin (try! (owner))
    (map-delete pending-adapters adapter)
    (match (map-get? adapters adapter) old (map-set adapters adapter (merge old {enabled:false})) true)
    (print {event:"adapter-revoked-v7",adapter:adapter})
    (ok true)))
(define-public (set-global-paused (value bool))
  (begin (try! (owner)) (var-set paused value)
    (print {event:"pause-v7",paused:value}) (ok value)))
(define-public (set-tvl-cap (cap uint))
  (begin (try! (owner))
    (asserts! (>= cap (var-get deposited)) ERR-CAP)
    (asserts! (> cap u0) ERR-CAP)
    (var-set tvl-cap cap)
    (print {event:"tvl-cap-v7",cap:cap}) (ok cap)))
(define-public (schedule-fee-basis-points (bps uint))
  (let ((at (+ burn-block-height DELAY)))
    (try! (owner)) (asserts! (<= bps MAX-FEE) ERR-FEE)
    (var-set pending-fee (some {bps:bps,at:at}))
    (print {event:"fee-scheduled-v7",bps:bps,at:at}) (ok at)))
(define-public (apply-fee-basis-points)
  (let ((pending (unwrap! (var-get pending-fee) ERR-PENDING)))
    (asserts! (>= burn-block-height (get at pending)) ERR-TIMELOCK)
    (var-set fee-bps (get bps pending)) (var-set pending-fee none)
    (print {event:"fee-applied-v7",bps:(get bps pending)}) (ok (get bps pending))))
(define-public (schedule-fee-collector (collector principal))
  (let ((at (+ burn-block-height DELAY)))
    (try! (owner)) (var-set pending-collector (some {collector:collector,at:at}))
    (print {event:"collector-scheduled-v7",collector:collector,at:at}) (ok at)))
(define-public (apply-fee-collector)
  (let ((pending (unwrap! (var-get pending-collector) ERR-PENDING)))
    (asserts! (>= burn-block-height (get at pending)) ERR-TIMELOCK)
    (var-set fee-collector (get collector pending)) (var-set pending-collector none)
    (print {event:"collector-applied-v7",collector:(get collector pending)}) (ok (get collector pending))))
(define-public (collect-fee (asset <token>))
  (let ((amount (var-get fee-balance)) (collector (var-get fee-collector)))
    (try! (owner)) (try! (lock)) (try! (check-token asset))
    (asserts! (> amount u0) ERR-AMOUNT)
    (var-set fee-balance u0)
    (asserts! (try! (as-contract (contract-call? asset transfer amount tx-sender collector none))) ERR-BALANCE)
    (var-set locked false)
    (print {event:"fee-collected-v7",amount:amount,collector:collector}) (ok amount)))

(define-read-only (get-position (user principal) (adapter principal)) (map-get? positions {user:user,adapter:adapter}))
(define-read-only (get-adapter-config (adapter principal)) (map-get? adapters adapter))
(define-read-only (get-adapter-deposited (adapter principal)) (default-to u0 (map-get? adapter-deposited adapter)))
(define-read-only (get-pending-adapter (adapter principal)) (map-get? pending-adapters adapter))
(define-read-only (get-sbtc-token) (var-get sbtc))
(define-read-only (get-tvl-cap) (var-get tvl-cap))
(define-read-only (get-total-deposited) (var-get deposited))
(define-read-only (get-fee-balance) (var-get fee-balance))
(define-read-only (get-fee-basis-points) (var-get fee-bps))
(define-read-only (get-fee-collector) (var-get fee-collector))
(define-read-only (get-pending-fee) (var-get pending-fee))
(define-read-only (get-pending-collector) (var-get pending-collector))
(define-read-only (is-global-paused) (var-get paused))
(define-read-only (get-owner) OWNER)
(define-read-only (get-min-deposit) MIN-DEPOSIT)
(define-read-only (get-timelock-blocks) DELAY)
