import {beforeEach,afterEach,describe,it,expect,vi} from 'vitest';
import {cvToHex,uintCV,responseOkCV,responseErrorCV} from '@stacks/transactions';
import {normalizeTxid,recordSubmittedCall,getSubmittedCalls,clearTransactionHistory,subscribeTransactions,parseCanonicalReceipt,fetchTransactionReceipt,type SubmittedCall} from '../../src/lib/transactionJournal.js';
const sender='SP2J6ZY48GV1EZ5V2V5RB9MP66SW86PYKKNRV9EJ7';
const KEY='satoshiyields.transaction-journal.v1';
const call:SubmittedCall={txid:'0x'+'a'.repeat(64),network:'mainnet',sender,contract:sender+'.vault-v7',functionName:'deposit',functionArgs:[cvToHex(uintCV(123))],postConditionMode:'deny',submittedAt:1};
const info={network_id:1,burn_block_height:100,stacks_tip_height:20};
function receipt(){return {tx_id:call.txid,sender:{address:sender},type:'contract_call',contract_call:{contract_id:call.contract,function_name:call.functionName,function_args:call.functionArgs.map(hex=>({hex}))},block:{height:10},bitcoin_block:{height:98},status:'success',result:{hex:cvToHex(responseOkCV(uintCV(123))),repr:'(ok u123)'}};}
beforeEach(()=>{localStorage.clear();vi.restoreAllMocks();});
afterEach(()=>{vi.unstubAllGlobals();});
describe('bounded local transaction journal',()=>{
 it('normalizes valid wallet IDs and rejects non-IDs',()=>{expect(normalizeTxid('B'.repeat(64))).toBe('0x'+'b'.repeat(64));for(const value of [null,42,'0x12','a'.repeat(65),'z'.repeat(64)])expect(()=>normalizeTxid(value)).toThrow();});
 it('persists exact requests, deduplicates IDs and rejects rebinding',()=>{const listener=vi.fn();const stop=subscribeTransactions(listener);recordSubmittedCall(call);recordSubmittedCall(call);expect(getSubmittedCalls()).toEqual([call]);expect(listener).toHaveBeenCalledTimes(1);expect(()=>recordSubmittedCall({...call,functionArgs:[]})).toThrow('another request');stop();});
 it('ignores corrupt, wrong-network, invalid-address and oversized saved history',()=>{for(const raw of ['{','{}',JSON.stringify([{...call,network:'devnet'},{...call,sender:'SPINVALID'},{...call,network:'testnet'},{...call,functionArgs:['0x1']}]),' '.repeat(1_000_001)]){localStorage.setItem(KEY,raw);expect(getSubmittedCalls()).toEqual([]);}});
 it('bounds history and clears only the selected address on the selected network',()=>{for(let i=0;i<105;i++)recordSubmittedCall({...call,txid:'0x'+i.toString(16).padStart(64,'0')});expect(getSubmittedCalls()).toHaveLength(100);expect(getSubmittedCalls()[0]!.txid).toBe('0x'+(104).toString(16).padStart(64,'0'));clearTransactionHistory('SP000000000000000000002Q6VF78','mainnet');expect(getSubmittedCalls()).toHaveLength(100);clearTransactionHistory(sender,'testnet');expect(getSubmittedCalls()).toHaveLength(100);clearTransactionHistory(sender,'mainnet');expect(getSubmittedCalls()).toEqual([]);});
 it('keeps a stable snapshot until storage changes',()=>{recordSubmittedCall(call);const first=getSubmittedCalls();expect(getSubmittedCalls()).toBe(first);localStorage.removeItem(KEY);expect(getSubmittedCalls()).toEqual([]);});
});
describe('canonical receipt verification',()=>{
 it('binds a successful receipt to the exact reviewed call and separates confirmations',()=>{expect(parseCanonicalReceipt(receipt(),call,info)).toMatchObject({state:'success',blockHeight:10,bitcoinConfirmations:3,contractResult:'(ok u123)'});});
 it.each(['network','sender','contract','function','argument','type','txid'])('rejects a mismatched %s',field=>{const tx=receipt();let node=info;if(field==='network')node={...info,network_id:0x80000000};if(field==='sender')tx.sender.address='SP000000000000000000002Q6VF78';if(field==='contract')tx.contract_call.contract_id=sender+'.other';if(field==='function')tx.contract_call.function_name='withdraw';if(field==='argument')tx.contract_call.function_args=[{hex:cvToHex(uintCV(124))}];if(field==='type')tx.type='token_transfer';if(field==='txid')tx.tx_id='0x'+'b'.repeat(64);expect(parseCanonicalReceipt(tx,call,node).state).toBe('mismatch');});
 it.each(['0x07','0x0701','0x0701'+'0'.repeat(32)+'00',cvToHex(responseErrorCV(uintCV(123))),cvToHex(uintCV(123))])('does not accept invalid successful contract result %s',hex=>{const tx=receipt();tx.result.hex=hex;expect(parseCanonicalReceipt(tx,call,info).state).toBe('unavailable');});
 it.each([0,-1,NaN,Infinity,101])('does not confirm an invalid Bitcoin inclusion height %s',height=>{const tx=receipt();tx.bitcoin_block.height=height;expect(parseCanonicalReceipt(tx,call,info).state).toBe('unavailable');});
 it('reports an asset guard failure without suggesting automatic retry',()=>{const tx=receipt();tx.status='abort_by_post_condition';expect(parseCanonicalReceipt(tx,call,info)).toMatchObject({state:'failed',detail:expect.stringContaining('asset-spending guards')});});
 it('does not turn an unknown status into success',()=>{const tx=receipt();tx.status='pending';expect(parseCanonicalReceipt(tx,call,info).state).toBe('unavailable');});
});
describe('live receipt reader',()=>{
 const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json'}});
 it('uses the current canonical v3 API and detects success',async()=>{const fetcher=vi.fn(async(url:string)=>json(url.endsWith('/v2/info')?info:receipt()));vi.stubGlobal('fetch',fetcher);expect((await fetchTransactionReceipt(call)).state).toBe('success');expect(fetcher.mock.calls[0]![0]).toContain('/extended/v3/transactions/');});
 it.each(['pending','dropped_replace_by_fee'])('detects %s only for the exact sender and transaction',async status=>{vi.stubGlobal('fetch',vi.fn(async(url:string)=>url.endsWith('/v2/info')?json(info):url.includes('/mempool/')?json({results:[{tx_id:call.txid,sender:{address:sender},status}]}):json({},404)));expect((await fetchTransactionReceipt(call)).state).toBe(status==='pending'?'pending':'dropped');});
 it('reports missing receipts as unknown and allows a former success to become unknown after reorganization',async()=>{let visible=true;vi.stubGlobal('fetch',vi.fn(async(url:string)=>url.endsWith('/v2/info')?json(info):url.includes('/mempool/')?json({results:[]}):visible?json(receipt()):json({},404)));expect((await fetchTransactionReceipt(call)).state).toBe('success');visible=false;expect((await fetchTransactionReceipt(call)).state).toBe('unavailable');});
 it('fails closed on endpoint errors',async()=>{vi.stubGlobal('fetch',vi.fn().mockRejectedValue(new Error('offline')));expect((await fetchTransactionReceipt(call))).toMatchObject({state:'unavailable',detail:'offline'});});
 it('does not query malformed saved destinations',async()=>{const fetcher=vi.fn();vi.stubGlobal('fetch',fetcher);expect((await fetchTransactionReceipt({...call,contract:sender+'.../evil'})).state).toBe('mismatch');expect(fetcher).not.toHaveBeenCalled();});
});
