import { Link } from "react-router-dom";
import { DEPOSITS_ENABLED, VAULT_VERSION } from "../constants/contracts.js";
import { networkName } from "../lib/stacksClient.js";
import { Icon } from "../components/shared/Icon.js";
const risks = [
  ["Smart contracts & administration", "A defect, unexpected adapter behavior, or compromised privileged key can put funds at risk. Contract controls and internal tests do not replace an independent review of the deployed code."],
  ["The asset you are holding", "BTC, sBTC, STX, and liquid staking receipts are distinct assets. Peg, signer, redemption, and bridge risks vary. A strategy that accepts STX cannot receive an sBTC deposit through the same route."],
  ["The strategy underneath", "Lending can face liquidity shortfalls or bad debt. Managed strategies may use leverage, off-chain counterparties, or external venues. An advertised rate does not establish safety or future returns."],
  ["The path back to your wallet", "An atomic withdrawal depends on available liquidity. A request-and-claim route depends on funding the redemption. Neither route guarantees that your original principal will be returned in full."],
  ["Data and execution", "Rate feeds and contract reads can fail or become stale. This interface hides unverified figures. A wallet returning a transaction ID means submitted; successful chain confirmation must be checked separately."],
];
export function Security() {
  return <main id="main-content" className="page-shell" tabIndex={-1}>
    <div className="page-intro"><div><p className="eyebrow">Risk & release</p><h1>Trust should be inspectable.</h1><p>The rebuild is a release candidate. This page explains what remains to verify and what can go wrong, without labeling the system audited or guaranteeing your principal.</p></div><Link className="text-link" to="/tvl">Inspect contracts <Icon name="external" size={13} /></Link></div>
    <div className="notice"><Icon name="shield" size={19} /><div><strong>{DEPOSITS_ENABLED ? "Testnet simulation access is enabled." : "New vault deposits are disabled for this deployment."}</strong> {networkName === "testnet" ? "Mock assets and adapters exercise the application’s mechanics. They do not demonstrate real protocol yield or mainnet readiness." : "Existing positions can be reviewed and withdrawal transactions requested. The configured legacy vault and the rebuild are separate deployments."}</div></div>
    <div className="notice" style={{ marginTop: 16 }}><Icon name="info" /><div><strong>Direct protocol connections have separate limits.</strong> Zest sBTC and StackingDAO stBTC routes verify current contracts before wallet review; funded mainnet fork tests cover deposits and exits. They have not received an independent audit here. New StackingDAO queue requests remain disabled until the bounded guard is deployed. Babylon and Lombard provide test-network preparation; native PoX-5 is an eligibility check. <Link to="/integrations">Inspect each connection</Link>.</div></div>
    <div className="risk-layout"><section aria-label="Risk factors">{risks.map(([title, description], index) => <article className="risk-item" key={title}><span className="mono">0{index + 1}</span><div><h3>{title}</h3><p>{description}</p></div></article>)}</section><aside className="release-panel"><h2>Before production vault deposits</h2><p>{VAULT_VERSION.toUpperCase()} configured on {networkName}. Enabling a route requires evidence for the exact deployed contracts.</p>{[["Independent security review", "Review the vault, each adapter, privileged roles, and the transaction flow; resolve material findings."], ["Integration verification", "Pin the actual protocol contracts and asset identifiers. Validate deposits, losses, fees, liquidity, and exits."], ["Public network evidence", "Confirm transactions and state changes on testnet. Mock integration success alone is insufficient."], ["Operational readiness", "Establish administration, monitoring, incident response, and a migration process for existing users."]].map(([title, description]) => <div className="release-gate" key={title}><span>{title}</span><small>{description}</small></div>)}<a className="text-link" style={{ marginTop: 15 }} href="https://github.com/soloking1412/SatoshiYield" target="_blank" rel="noopener noreferrer">Review the source <Icon name="external" size={13} /></a></aside></div>
    <div className="notice"><Icon name="info" size={18} /><div><strong>There is no universally safest or highest-yield route.</strong> Returns, asset exposure, liquidity, administration, and custody assumptions must be assessed together. Only an explicitly enabled, reviewed integration can accept deposits through this app.</div></div>
  </main>;
}
