import { Link } from "react-router-dom";
import { useVaultStats } from "../hooks/useVaultStats.js";
import { CONTRACTS, VAULT_VERSION, DEPOSITS_ENABLED } from "../constants/contracts.js";
import { networkName } from "../lib/stacksClient.js";
import { Icon } from "../components/shared/Icon.js";

export function TVL() {
  const { data, isLoading, isError, refetch, dataUpdatedAt } = useVaultStats();
  const stats = isError ? undefined : data;
  const sats = (value: number | undefined) => value === undefined ? "—" : (value / 1e8).toFixed(8);
  const contracts = [["Vault", CONTRACTS.VAULT], ["sBTC token", CONTRACTS.SBTC_TOKEN], ...Object.entries(CONTRACTS.ADAPTERS).map(([key, value]) => [`${key === "zest" ? "Zest" : "Hermetica"} adapter`, value])];
  return <main id="main-content" className="page-shell" tabIndex={-1}>
    <div className="page-intro"><div><p className="eyebrow">Contracts, capital & constraints</p><h1>A view into the vault.</h1><p>Direct contract readings, with their scope clearly labeled. Deposited principal is an accounting value; it is not a mark-to-market valuation or a measure of withdrawal liquidity.</p></div><button className="btn ghost" onClick={() => void refetch()} disabled={isLoading}><Icon name="refresh" size={14} />Refresh data</button></div>
    <div className="directory-meta"><span className="mono">{VAULT_VERSION.toUpperCase()} / {networkName.toUpperCase()}</span><span>{isLoading ? "Reading contract…" : isError ? "Data unavailable" : dataUpdatedAt ? `Read at ${new Date(dataUpdatedAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}` : "No contract reading"}</span></div>
    {isError && <div className="notice error" role="alert"><Icon name="info" /><div><strong>The vault could not be read.</strong> Values are unavailable until a complete contract response succeeds. Please retry.</div></div>}
    <dl className="metrics" aria-busy={isLoading}><div className="metric"><dt>Recorded deposited principal</dt><dd>{sats(stats?.totalDepositedSats)}<small>sBTC</small></dd><p>Vault accounting · excludes unreported returns</p></div><div className="metric"><dt>Configured deposit cap</dt><dd>{sats(stats?.tvlCapSats)}<small>sBTC</small></dd><p>A capacity limit, not a protection guarantee</p></div><div className="metric"><dt>Performance fee</dt><dd>{stats ? (stats.feeBasisPoints / 100).toFixed(2) : "—"}<small>%</small></dd><p>Vault fee on yield, when realized</p></div></dl>
    <div className="telemetry-grid"><section><div className="section-heading"><h2>Historical deposits</h2><span className="status-label neutral">Not available</span></div><div className="history-empty"><Icon name="chart" size={35} /><h3>A time series needs real snapshots.</h3><p>Historical vault snapshots are not connected to this view yet. No estimated or simulated performance chart is shown.</p></div></section><section><div className="section-heading"><h2>Vault parameters</h2></div><dl className="definition-list"><div><dt>Minimum deposit</dt><dd>{sats(stats?.minDepositSats)} sBTC</dd></div><div><dt>Accrued vault fees</dt><dd>{sats(stats?.feeBalanceSats)} sBTC</dd></div><div><dt>New deposits</dt><dd><span className="status-label warning">{DEPOSITS_ENABLED ? "Enabled by configuration" : "Disabled for review"}</span></dd></div><div><dt>Contract version</dt><dd>{VAULT_VERSION}</dd></div><div><dt>Network</dt><dd style={{ textTransform: "capitalize" }}>{networkName}</dd></div></dl><p className="directory-footnote">Application availability and the contract’s on-chain state are separate. A successful read does not establish that a contract is safe.</p></section></div>
    <section><div className="section-heading"><div><h2>Verify at the source.</h2><p>Configured contracts for this environment. Always check the network and exact address.</p></div><Link className="text-link" to="/security">Release status <Icon name="arrow" size={13} /></Link></div><div>{contracts.map(([label, principal]) => <div className="contract-row" key={label}><span>{label}</span><span className="contract-address">{principal || "Not configured"}</span>{principal ? <a className="text-link" href={`https://explorer.hiro.so/address/${principal}?chain=${networkName}`} target="_blank" rel="noopener noreferrer">Explorer <Icon name="external" size={12} /></a> : <span className="text-muted small">Unavailable</span>}</div>)}</div></section>
  </main>;
}
